server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: trackme-core
#  config:
#    import: optional:configserver:http://127.0.0.1:8888
#  cloud:
#    config:
#      name: trackme-config
  datasource:
    url: jdbc:postgresql://localhost:5432/trackme
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath*:initdata/batch-postgresql.sql
      mode: always