server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: trackme-core
  datasource:
    url: jdbc:postgresql://localhost:5432/trackme
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath*:initdata/batch-postgresql.sql
      mode: always